name: Deployment Pipeline

on:
  push:
    branch:
    - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]
jobs:
  main_deployement_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install npm
        run: npm install
      - name: LINT THIS MF
        run: npm run eslint
      - name: BUILD A WALL
        run: npm run build
      - name: TEST PLEASE
        run: npm run test
      - name: TRIGGER Deployment
        if: ${{ github.event_name == 'push' }} 
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_SERVICE_KEY }}

  tag_release:
    needs: [main_deployement_pipeline]
    if: >-
      ${{ github.event_name == 'push' &&
        !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version number and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true        